### ISSUE TITLE
Product Page Features Layout

### ISSUE THREAD

**Issue by ohnno** [ohnno/Brosa#19]
Location: Product Page
Browser: Firefox
OS: OS X Mavericks
Screen: Laptop

The feature section (the left/right image/text layout), the last highlight's layout is not correct. Displaying inline on the right rather than below the previous item.

**Comment by limcolin** [comment]
johnny can you clarify please

**Comment by limcolin** [comment]
font is wrong for some sections of this too. need to fix

**Comment by limcolin** [comment]
i think the layout is correct. If I am understanding correctly, you mean the final photo is on the same line as the 3rd photo(e.g. it's in the 3rd row as opposed to being on the fourth)?
That is the intended design.

Also fixed the incorrect font for the 3rd set of text. BUT I NEED TO CHECK THE FINAL DATA THAT THE ADMINS HAVE DONE. Depending on a minor detail, I may or may not have to make a slight modification to the code

**Comment by ohnno** [comment]
This issue has not been resolved, please find attached a screenshot of the issue (Firefox).

![screenshot](https://cloud.githubusercontent.com/assets/2937538/8688753/34d207b6-2ae3-11e5-9900-1d02439d45f2.png)

**Comment by limcolin** [comment]
RESOLVED! :dancers:
