### ISSUE TITLE
Responsive Top Navigation

### ISSUE THREAD

**Issue by ohnno** [ohnno/Brosa#39]
Location: Top Navigation
Browser: Firefox
OS: OS X Mavericks
Screen: Mobile

1. For mobile, remove all top navigation with the exception of the menu button (hamburger).
2. Inside this menu, add the cart.
3. Inside this menu, add a search option.
4. Inside this menu, add a phone number (this should be a 'tel:' field, so tapping on it on a phone should prompt a call).

**Comment by limcolin** [comment]
Also, when mobile menu is open, there is no way to close it other than click on the black area which is very small with the menu open
