### ISSUE TITLE
Product Page White Space Bug

### ISSUE THREAD

**Issue by ohnno** [ohnno/Brosa#45]
Location: Product Page
Browser: Chrome
OS: OS X Mavericks
Screen: Laptop

Attached is a screenshot of a product page I stumble across; it happens between the product information (hero) and the "From the collection" link. Seems like I can replicate it, not sure if it was always like this and what caused it.

Update: Doesn't seem to happen all of the time, but has happened more than once.

![screenshot-2](https://cloud.githubusercontent.com/assets/2937538/8643547/9028f122-2978-11e5-94f5-f3fd1fc88806.png)

**Comment by limcolin** [comment]
can you send me the link of a product that has this bug occurring please?

**Comment by ohnno** [comment]
can't seem to replicate it anymore, not sure what changed haha. I'll close this until it happens again.
