### ISSUE TITLE
create color selector image files 

### ISSUE THREAD

**Issue by davidywei** [ohnno/Brosa#66]
@ohnno just marking it out as this needs to be done before launch.

how to is here:
https://docs.shopify.com/manual/configuration/store-customization/showcasing-products/add-color-swatches-to-your-products

there's a section on 'uploading your own color files'.

I have the list of colours I can pull out. Only slight roadblock now is I want to wait for Colin to confirm the size of this little 'colour square' we need to export and we do a test before doing them all.

**Comment by ohnno** [comment]
Yep sounds good,

When I put them together it will probably be in pretty hi res anyway (and would just export them out to whatever size needed), less restrictive this way if you need a larger version later or for retina.

So could potentially start on this immediately if need be.
